const PROPERTY_NAME_MAP = {
    HP: '生命值',
    DEF: '防御力',
    ATK: '攻击力',
    proficiency: '元素精通',
    critRate: '暴击率',
    proportionalDamage: '暴击伤害',
    elementRate: '所有元素伤害加成',
    elementRateF: '火元素伤害加成',
    elementRateW: '水元素伤害加成',
    elementRateI: '冰元素伤害加成',
    elementRateS: '土元素伤害加成',
    elementRateA: '风元素伤害加成',
    elementRateE: '雷元素伤害加成',
    elementRateP: '物理伤害加成',
    energyRate: '元素充能效率',

    reactionRateExtra: '反应系数加成',

    treatment: '治疗加成',
    damageRateExtra: '所有伤害加成',
    damageRateExtraAN: '普攻/重击伤害加成',
    damageRateExtraA: '普攻伤害加成',
    damageRateExtraN: '重击伤害加成',
    damageRateExtraD: '下落伤害加成',
    damageRateExtraE: '元素战技伤害加成',
    damageRateExtraQ: '元素爆发伤害加成',
    originalDamageExtra: '原始伤害加成',
    ATKToOriginalDamageExtra: '伤害提高攻击力的比例',
    HPToOriginalDamageExtra: '伤害提高生命值的比例',

    reduceResRate: '所有抗性减少',
    reduceResRateEle: '所有元素抗性减少',
    reduceDefRate: '防御力降低',

    spear: '长柄武器',
    claymore: '双手剑',
    sword: '单手剑',
    bow: '弓箭',
    grimoire: '法器',

    flower: '生之花',
    feather: '死之羽',
    hourglass: '时之沙',
    cup: '空之杯',
    hat: '理之冠',

    F: 'fire',
    W: 'water',
    I: 'ice',
    S: 'soil',
    A: 'air',
    E: 'electric',
    P: 'physics',

    fire: '火',
    water: '水',
    ice: '冰',
    soil: '土',
    air: '风',
    electric: '雷',
    physics: '物理',

    生之花: 'flower',
    死之羽: 'feather',
    时之沙: 'hourglass',
    空之杯: 'cup',
    理之冠: 'hat',
    生命值: 'HP',
    防御力: 'DEF',
    攻击力: 'ATK',
    元素精通: 'proficiency',
    暴击率: 'critRate',
    暴击伤害: 'proportionalDamage',
    火元素伤害加成: 'elementRateF',
    水元素伤害加成: 'elementRateW',
    冰元素伤害加成: 'elementRateI',
    土元素伤害加成: 'elementRateS',
    风元素伤害加成: 'elementRateA',
    雷元素伤害加成: 'elementRateE',
    物理伤害加成: 'elementRateP',
    元素充能效率: 'energyRate',
    治疗加成: 'treatment',
}

export default PROPERTY_NAME_MAP
